# Copyright Adfinis 2025, 2026
# SPDX-License-Identifier: GPL-3.0-or-later

---
services:
  bastion:
    image: ghcr.io/adfinis-forks/the-bastion:sandbox@sha256:0405abab0ca0fa736ceea458f9972a78c8bc174da2b78eac17ec9e1b73fdc6b7
    ports:
      - "2222:22"
