// Copyright (c) Adfinis
// SPDX-License-Identifier: GPL-3.0-or-later

package provider

import (
	"os"
	"testing"

	"github.com/hashicorp/terraform-plugin-framework/providerserver"
	"github.com/hashicorp/terraform-plugin-go/tfprotov6"
)

var testAccProtoV6ProviderFactories = map[string]func() (tfprotov6.ProviderServer, error){
	"bastion": providerserver.NewProtocol6WithError(New("test")()),
}

func testAccPreCheck(t *testing.T) {
	// Check if running in acceptance test mode
	if os.Getenv("TF_ACC") == "" {
		t.Skip("TF_ACC must be set for acceptance tests")
	}
}

func providerConfig() string {
	host := os.Getenv("BASTION_HOST")
	if host == "" {
		host = "localhost"
	}

	port := os.Getenv("BASTION_PORT")
	if port == "" {
		port = "2222"
	}

	username := os.Getenv("BASTION_USERNAME")
	if username == "" {
		username = "bastionadmin"
	}

	privateKeyFile := os.Getenv("BASTION_PRIVATE_KEY_FILE")
	if privateKeyFile == "" {
		// Use the test key generated by the Makefile
		privateKeyFile = "../../ssh-keys/id_ed25519"
	}

	return `
provider "bastion" {
  host              = "` + host + `"
  port              = ` + port + `
  username          = "` + username + `"
  private_key_file  = "` + privateKeyFile + `"
  strict_host_key_checking = false
}
`
}
